### ISSUE TITLE
Can we make it even faster?

### ISSUE THREAD

**Issue by will-r-chase** [coolbutuseless/poissoned#1]
20x faster sampler according to this blog post... probably a simple change? I could try it out when I get back to generative stuff, but might not have time for a while, so putting this here just in case you want to look 

http://extremelearning.com.au/an-improved-version-of-bridsons-algorithm-n-for-poisson-disc-sampling/

With the vectorized R code and your tiling solution, could this be the fastest poisson disc algorithm out there? 😃

**Comment by coolbutuseless** [comment]
Had a look. And i've implemented this shortcut for the 3D case, but the 2D case samples from the annular section from 'r' to '2r' as described in Bridson's paper.
